---
- name: User Setup for lkarasinski
  hosts: localhost
  become: yes
  vars:
    new_user: "lkarasinski"
    user_shell: "/usr/bin/fish"
  tasks:
    - name: Ensure the user exists
      user:
        name: "{{ new_user }}"
        shell: "{{ user_shell }}"
        groups: sudo
        append: yes
    - name: Install fish, tmux, nvim, and required packages for Docker
      package:
        name:
          - fish
          - tmux
          - neovim
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    - name: Set fish as default shell for the user
      user:
        name: "{{ new_user }}"
        shell: "{{ user_shell }}"
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    - name: Add user to docker group
      user:
        name: "{{ new_user }}"
        groups: docker
        append: yes
    - name: Add ~/.local/bin to PATH in .profile
      become_user: "{{ new_user }}"
      blockinfile:
        path: "/home/{{ new_user }}/.profile"
        create: yes
        block: |
          # set PATH so it includes user's private bin if it exists
          if [ -d "$HOME/.local/bin" ] ; then
              PATH="$HOME/.local/bin:$PATH"
          fi
    - name: Add ~/.local/bin to PATH in fish config
      become_user: "{{ new_user }}"
      blockinfile:
        path: "/home/{{ new_user }}/.config/fish/config.fish"
        create: yes
        block: |
          if not contains ~/.local/bin $PATH
            set -gx PATH ~/.local/bin $PATH
          end
    - name: Ensure .tmux.conf exists
      file:
        path: "/home/{{ new_user }}/.tmux.conf"
        state: touch
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: '0644'
    - name: Add basic tmux configuration
      lineinfile:
        path: "/home/{{ new_user }}/.tmux.conf"
        line: "set -g mouse on"
        create: yes
