name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.1'

    - name: Build
      run: go build -v -o lxc-setup ./...

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: lxc-setup
        tag_name: ${{ steps.date.outputs.date }}
        name: Release ${{ steps.date.outputs.date }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
